# Generated by Django 4.1.1 on 2022-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('numero', models.CharField(max_length=3, verbose_name='Edad')),
                ('equipo', models.CharField(max_length=50, verbose_name='Equipo')),
                ('posicion', models.CharField(max_length=50, verbose_name='Posicion')),
                ('estadio', models.CharField(max_length=50, verbose_name='Estadio')),
            ],
        ),
    ]
