# Generated by Django 4.1.1 on 2022-09-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='numero',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='jugadores',
            name='numero_playera',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de playera'),
        ),
    ]
